use ARALUEN_DATAVAULT;
use schema LOAD_NDIS;
use warehouse ARALUEN;
put file://D:\BI\DATA\input_file.csv @STAGE_NDIS;
COPY INTO ARALUEN_DATAVAULT.DATAVAULT."ATTRIBUTED_PROFIT_AND_LOSS" FROM @STAGE_NDIS file_format='LOAD_CSM.CSVFORMAT';
remove @STAGE_NDIS pattern='.*.csv.gz';
